Python 3.11.7
starting zsts_to_post_csv
done with globals
starting
Reading submissions

Traceback (most recent call last):
  File "/home/bls910/reddit/preprocess/zsts_to_post_csv.py", line 132, in <module>
    Tile.render_content()
  File "/home/bls910/reddit/preprocess/zsts_to_post_csv.py", line 124, in render_content
    lines_read = self.process_zst(writer, self.submissions_zst_path, "submission")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/reddit/preprocess/zsts_to_post_csv.py", line 37, in process_zst
    for line, file_bytes_processed in self.read_lines_zst(path):
  File "/home/bls910/reddit/preprocess/zsts_to_post_csv.py", line 85, in read_lines_zst
    with open(file_name, 'rb') as file_handle:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/projects/p32275/FantasyFootball/FantasyFootball_submissions.zst'
starting zsts_to_user_data.py
done with globals
starting
Reading submissions
Traceback (most recent call last):
  File "/home/bls910/reddit/preprocess/zsts_to_user_data.py", line 140, in <module>
    Tile.render_content()
  File "/home/bls910/reddit/preprocess/zsts_to_user_data.py", line 124, in render_content
    lines_read = self.process_zst(self.submissions_zst_path, "submission")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/reddit/preprocess/zsts_to_user_data.py", line 42, in process_zst
    file_size = os.stat(path).st_size
                ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/projects/p32275/FantasyFootball/FantasyFootball_submissions.zst'
starting clean_and_add_seconds.py
done with globals
starting
Traceback (most recent call last):
  File "/home/bls910/reddit/preprocess/clean_and_add_seconds.py", line 211, in <module>
    Tile.render_content()
  File "/home/bls910/reddit/preprocess/clean_and_add_seconds.py", line 176, in render_content
    user_df = load_pickle_or_parquet(self.user_data_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/reddit/preprocess/clean_and_add_seconds.py", line 59, in load_pickle_or_parquet
    return pd.read_parquet(path)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 667, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 267, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/projects/p32275/FantasyFootball/FantasyFootball_user_data.parquet'
starting tokenize_cleaned_csv.py
done with globals
starting
reading to dask and processing
getting total rows
Traceback (most recent call last):
  File "/home/bls910/reddit/preprocess/tokenize_cleaned_csv_new2.py", line 122, in <module>
    Tile.render_content()
  File "/home/bls910/reddit/preprocess/tokenize_cleaned_csv_new2.py", line 90, in render_content
    total_rows = sum(1 for row in open(self.csv_path)) - 1  # Subtract 1 for the header
                                  ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/projects/p32275/FantasyFootball/FantasyFootball_prep.csv'
starting add_true_date_info.py
done with globals
starting
reading
Traceback (most recent call last):
  File "/home/bls910/reddit/preprocess/add_true_date_info.py", line 90, in <module>
    Tile.render_content()
  File "/home/bls910/reddit/preprocess/add_true_date_info.py", line 60, in render_content
    df = load_pickle_or_parquet(self.df_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/reddit/preprocess/add_true_date_info.py", line 16, in load_pickle_or_parquet
    return pd.read_parquet(path)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 667, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 267, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/projects/p32275/FantasyFootball/FantasyFootball_df.parquet'
starting zsts_to_exp_df
done with globals
starting
Reading submissions

Traceback (most recent call last):
  File "/home/bls910/reddit/preprocess_exp/zsts_to_exp_df.py", line 114, in <module>
    Tile.render_content()
  File "/home/bls910/reddit/preprocess_exp/zsts_to_exp_df.py", line 106, in render_content
    res_lines = self.process_zst(self.submissions_zst_path, "submission")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/reddit/preprocess_exp/zsts_to_exp_df.py", line 39, in process_zst
    for line, file_bytes_processed in self.read_lines_zst(path):
  File "/home/bls910/reddit/preprocess_exp/zsts_to_exp_df.py", line 72, in read_lines_zst
    with open(file_name, 'rb') as file_handle:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/projects/p32275/FantasyFootball/FantasyFootball_submissions.zst'
starting clean_and_add_seconds.py
done with globals
starting
Traceback (most recent call last):
  File "/home/bls910/reddit/preprocess_exp/add_seconds.py", line 176, in <module>
    Tile.render_content()
  File "/home/bls910/reddit/preprocess_exp/add_seconds.py", line 144, in render_content
    user_df = load_pickle_or_parquet(self.user_data_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/reddit/preprocess_exp/add_seconds.py", line 51, in load_pickle_or_parquet
    return pd.read_parquet(path)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 667, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 267, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/projects/p32275/FantasyFootball/FantasyFootball_user_data.parquet'
starting add_true_date_info.py
done with globals
starting
reading
Traceback (most recent call last):
  File "/home/bls910/reddit/preprocess_exp/add_true_date_info.py", line 129, in <module>
    Tile.render_content()
  File "/home/bls910/reddit/preprocess_exp/add_true_date_info.py", line 90, in render_content
    df = load_pickle_or_parquet(self.df_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/reddit/preprocess_exp/add_true_date_info.py", line 21, in load_pickle_or_parquet
    return pd.read_parquet(path)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 667, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 267, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/bls910/.conda/envs/first-kernel/lib/python3.11/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/projects/p32275/FantasyFootball/FantasyFootball_df_exp_seconds.parquet'
python: can't open file '/home/bls910/reddit/preprocess_exp/characterize.py': [Errno 2] No such file or directory
